#!/usr/bin/env python3
"""Generate a SYNTHETIC building dataset so Shadey can demonstrate sun/shade
without bundling a large real-world extract.

This does NOT need network access. It lays out a plausible grid of perimeter
city blocks (Berlin-style ~5-storey Altbau) around one or more centres, leaving
the centre cell open as a plaza. Output is GeoJSON in lng,lat order with a
`height` (metres) property, exactly the shape the app and the real Overpass
pipeline produce.

Replace the output with real data using fetch_osm.py for production use.
"""
from __future__ import annotations

import json
import math
import random
from pathlib import Path

# (name, lat, lng) centres to build blocks around.
CENTERS = [
    ("Boxhagener Platz", 52.51028, 13.45853),
]

CELL_M = 64.0          # block pitch (building + street)
BUILDING_M = 46.0      # building block size
GRID_RADIUS = 4        # cells in each direction from centre
SEED = 20260601


def meters_to_latlng(lat0: float, lng0: float, east_m: float, north_m: float):
    dlat = north_m / 111_320.0
    dlng = east_m / (111_320.0 * math.cos(math.radians(lat0)))
    return lat0 + dlat, lng0 + dlng


def block_polygon(lat0, lng0, cx_m, cy_m, size_m):
    half = size_m / 2.0
    corners_m = [(-half, -half), (half, -half), (half, half), (-half, half), (-half, -half)]
    ring = []
    for ex, ny in corners_m:
        lat, lng = meters_to_latlng(lat0, lng0, cx_m + ex, cy_m + ny)
        ring.append([round(lng, 7), round(lat, 7)])
    return ring


def build():
    rng = random.Random(SEED)
    features = []
    fid = 0
    for name, lat0, lng0 in CENTERS:
        for i in range(-GRID_RADIUS, GRID_RADIUS + 1):
            for j in range(-GRID_RADIUS, GRID_RADIUS + 1):
                if i == 0 and j == 0:
                    continue  # leave the plaza open
                # vary footprint and skip a few cells for irregularity
                if rng.random() < 0.08:
                    continue
                size = BUILDING_M * rng.uniform(0.85, 1.0)
                levels = rng.choice([4, 5, 5, 6, 6, 7])
                height = round(levels * 3.2 + rng.uniform(-0.5, 1.5), 1)
                ring = block_polygon(lat0, lng0, i * CELL_M, j * CELL_M, size)
                features.append({
                    "type": "Feature",
                    "id": f"sample-{fid}",
                    "properties": {
                        "height": height,
                        "building:levels": levels,
                        "synthetic": True,
                        "near": name,
                    },
                    "geometry": {"type": "Polygon", "coordinates": [ring]},
                })
                fid += 1

    return {
        "type": "FeatureCollection",
        "note": "SYNTHETIC sample buildings generated by make_sample.py. "
                "Not real OSM data. Replace with fetch_osm.py output for production.",
        "features": features,
    }


def main():
    out = Path(__file__).resolve().parents[1] / "app/src/main/assets/data/sample_buildings.geojson"
    out.parent.mkdir(parents=True, exist_ok=True)
    fc = build()
    out.write_text(json.dumps(fc, separators=(",", ":")))
    print(f"Wrote {len(fc['features'])} synthetic buildings to {out}")


if __name__ == "__main__":
    main()
